AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation VPC Template
#
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
Resources:
  MonVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: 'MainVPC'

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3a
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: 'MainVPC-private-a'
      VpcId: !Ref MonVPC

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3b
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: 'MainVPC-private-b'
      VpcId: !Ref MonVPC

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3a
      CidrBlock: 10.0.100.0/24
      Tags:
        - Key: Name
          Value: 'MainVPC-public-a'
      VpcId: !Ref MonVPC

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3b
      CidrBlock: 10.0.101.0/24
      Tags:
        - Key: Name
          Value: 'MainVPC-public-b'
      VpcId: !Ref MonVPC
  FirstWPServ:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-3a
      ImageId: ami-0f4c4d9ba38fd756e
      InstanceType: t2.micro
  SecondWPServ:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-west-3a
      ImageId: ami-0f4c4d9ba38fd756e
      InstanceType: t2.micro

# EFS AWS pour WP et BDD